version: '3.9'

services:
  db:
    image: postgres:15.1
    env_file:
      - src/traffic_app/.env
    volumes:  
      - postgres_data:/var/lib/postgresql/data/ 

  django:
    environment:
      - DATABASE_URL=postgres://dannys:132dannys@db:5432/traffic
    build: .
    command: bash -c "python /web-app/src/manage.py migrate && python /web-app/src/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/web-app
    ports:
      - 8000:8000
    depends_on:
      - db

  redis:
    image: redis:7.0.5-alpine
    hostname: redis 

  worker:
    build: 
      context: .
    hostname: worker
    entrypoint: celery
    command: ["-A", "celery_app.app", "worker", "--loglevel", "info"]
    volumes:
      - .:/web-app
    links:
      - redis
    depends_on:
      - redis  
      - db  

volumes:
  postgres_data: